USER_ID_COLUMN = 'user'
ITEM_ID_COLUMN = 'adgroup_id'
DT_COLUMN = 'time_stamp'
TARGET_COLUMN = 'clk'
Y_REC_COLUMN = 'y_rec'

GROUP_COLUMN = 'group_id'
RELEVANCE_COLUMN = 'relevance'
Y_PRED_COLUMN = 'y_pred'
Y_TRUE_COLUMN = 'y_true'
